ArvidsBowling/Models/ErrorViewModel.cs
using System;

namespace ArvidsBowling.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ArvidsBowling/Models/Home/CustomerInfoVM.cs
using ArvidsBowling.Data;
using System.Collections.Generic;

namespace ArvidsBowling.Models.Home
{
    public class CustomerInfoVM
    {
        public Customer Customer { get; set; }
        public IList<Account> Accounts { get; set; }

        public CustomerInfoVM()
        {
            Accounts = new List<Account>();
        }
    }
}

ArvidsBowling/Models/Transaction/AccountVM.cs
using System.ComponentModel.DataAnnotations;
using ArvidsBowling.Data;

namespace ArvidsBank.Models.Transaction
{
    public class AccountVM
    {
        [Display(Name = "Kontonummer")]
        public string AccountNr { get; set; }

        [Display(Name = "Saldo")]
        public decimal Amount { get; set; }

        public static AccountVM Create(Account account)
        {
            return new AccountVM
            {
                AccountNr = account.AccountNr,
                Amount = account.Balance
            };
        }
    }
}

ArvidsBowling/Models/Transaction/TransactionVM.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ArvidsBank.Models.Transaction
{
    public class TransactionVM
    {
        [Display(Name = "Belopp")]
        public decimal Amount { get; set; }

        [Display(Name = "Kontonummer")]
        [Required(ErrorMessage = "Kontonummer måste anges")]
        public string AccountNum { get; set; }
    }
}

ArvidsBowling/Models/Transfer/TransferVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using ArvidsBank.Models.Transaction;

namespace ArvidsBank.Models.Transfer
{
    public class TransferVM
    {
        [Display(Name = "Belopp")]
        public decimal Amount { get; set; }

        [Display(Name = "Från konto")]
        [Required(ErrorMessage = "Kontonummer måste anges")]
        public string fromAccountNumber { get; set; }

        [Display(Name = "Till konto")]
        [Required(ErrorMessage = "Kontonummer måste anges")]
        public string recievingAccountNumber { get; set; }



        public AccountVM FromAccount { get; set; }
        public AccountVM RecievingAccount { get; set; }
    }
}

ArvidsBowling/Controllers/HomeController.cs
using ArvidsBowling.Data;
using ArvidsBowling.Models;
using ArvidsBowling.Models.Home;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace ArvidsBowling.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var model = new List<CustomerInfoVM>();
            var repo = BankRepository.Instance();
            var accounts = repo.Accounts;

            foreach (var customer in repo.Customers)
            {
                var customerAccounts = accounts.Where(a => a.CustomerId == customer.Id).ToList();
                model.Add(new CustomerInfoVM() { Customer = customer, Accounts = customerAccounts });
            }
            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ArvidsBowling/Controllers/TransactionController.cs
using System;
using ArvidsBank.Models.Transaction;
using ArvidsBowling.Data;
using Microsoft.AspNetCore.Mvc;

namespace ArvidsBank.Controllers
{
    public class TransactionController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Withdraw(TransactionVM model)
        {
            var repo = BankRepository.Instance();

            if (ModelState.IsValid)
            {
                try
                {
                    var account = repo.GetAccount(model.AccountNum);
                    repo.Withdrawal(account, model.Amount);

                    var accountVm = AccountVM.Create(account);
                    return View("TransactionSuccess", accountVm);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            return View("Index", model);

        }

        public IActionResult Deposit(TransactionVM model)
        {
            var repo = BankRepository.Instance();

            if (ModelState.IsValid)
            {
                try
                {
                    var account = repo.GetAccount(model.AccountNum);
                    repo.Deposit(account, model.Amount);

                    var accountVM = AccountVM.Create(account);
                    return View("TransactionSuccess", accountVM);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            return View("Index", model);
        }
    }
}

ArvidsBowling/Controllers/TransferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ArvidsBank.Models.Transaction;
using ArvidsBank.Models.Transfer;
using ArvidsBowling.Data;
using Microsoft.AspNetCore.Mvc;

namespace ArvidsBank.Controllers
{
    public class TransferController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Transfer(TransferVM model)
        {
            var repo = BankRepository.Instance();

            if (ModelState.IsValid)
            {
                try
                {
                    var fromAccount = repo.GetAccount(model.fromAccountNumber);
                    var recievingAccount = repo.GetAccount(model.recievingAccountNumber);

                    repo.Transfer(fromAccount,recievingAccount,model.Amount);

                    var transferVM = new TransferVM();
                    transferVM.FromAccount = AccountVM.Create(fromAccount);
                    transferVM.RecievingAccount = AccountVM.Create(recievingAccount);
                    return View("TransferSuccess", transferVM);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            return View("Index", model);

        }
    }

}

ArvidsBowling/Views/Home/Index.cshtml
@using ArvidsBowling.Models.Home
@model IList<CustomerInfoVM>

@{
    ViewData["Title"] = "Home Page";
}
<style>
    table, th, td {
        border: 1px solid black;
    }
    
    .td-right{
        text-align: right;
    }
</style>

<div class="row">
    <div class="col-12">
        <table style="border: 1px solid black;">
            <tr>
                <th>Id</th>
                <th>Förnamn</th>
                <th>Efternamn</th>
                <th>Konto</th>
                <th>Saldo</th>
            </tr>
            @foreach (var viewModel in Model)
            {
                <tr>
                    <td>@viewModel.Customer.Id</td>
                    <td>@viewModel.Customer.FirstName</td>
                    <td>@viewModel.Customer.LastName</td>
                    @if (viewModel.Accounts.Count() == 0)
                    {
                        <td>Inget konto</td>
                        <td></td>
                    }
                    else
                    {
                        <td class="td-right">@viewModel.Accounts[0].AccountNr</td>
                        <td class="td-right">@String.Format("{0:N}", viewModel.Accounts[0].Balance) kr</td>
                    }
                </tr>
                @for (int i = 1; i < viewModel.Accounts.Count(); i++)
                {
                    <tr>
                        <td>@viewModel.Customer.Id</td>
                        <td></td>
                        <td></td>
                        <td class="td-right">@viewModel.Accounts[i].AccountNr</td>
                        <td class="td-right">@String.Format("{0:N}", viewModel.Accounts[i].Balance) kr</td>
                    </tr>
                }
            }
        </table>
    </div>
</div>

ArvidsBowling/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Arvids Bank</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Arvids Bank</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Transaction" asp-action="Index">Transaktion</a></li>
                    <li><a asp-area="" asp-controller="Transfer" asp-action="Index">Överföring</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Arvids Bank</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

ArvidsBowling/Views/Transaction/Index.cshtml
@using ArvidsBank.Models.Transaction
@model ArvidsBank.Models.Transaction.TransactionVM

@{
    ViewData["Title"] = "Transaction";
}

<form asp-controller="Transaction" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="AccountNum"></label>
        <input asp-for="AccountNum" class="form-control"/>
        <span asp-validation-for="AccountNum" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Amount"></label>
        <input asp-for="Amount" class="form-control"/>
        <span asp-validation-for="Amount" class="text-danger"></span>
    </div>
    <button type="submit" asp-action="Deposit">Insättning</button>
    <button type="submit" asp-action="Withdraw" class="pull-right">Uttag</button>
</form>

<br/>
<br/>
<a asp-controller="Home" asp-action="Index" class="btn btn-primary">Tillbaka</a>

ArvidsBowling/Views/Transaction/TransactionSuccess.cshtml
@model ArvidsBank.Models.Transaction.AccountVM

@{
    ViewData["Title"] = "Transaktion lyckades";
}

<div class="row">
    <div class="col-xs-12">
        <h1>Transaktion lyckades</h1>
        <table>
            <tr>
                <th>Konto</th>
                <th>Saldo</th>
            </tr>
            <tr>
                <td>@Model.AccountNr</td>
                <td>@String.Format("{0:N}", @Model.Amount) kr</td>
            </tr>
        </table>
    </div>
</div>

<br/>
<br/>
<a asp-controller="Home" asp-action="Index" class="btn btn-primary">Tillbaka</a>

ArvidsBowling/Views/Transfer/Index.cshtml
@using ArvidsBank.Models.Transaction
@model ArvidsBank.Models.Transfer.TransferVM

@{
    ViewData["Title"] = "Transaction";
}

<form asp-controller="Transfer" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="fromAccountNumber"></label>
        <input asp-for="fromAccountNumber" class="form-control" />
        <span asp-validation-for="fromAccountNumber" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="recievingAccountNumber">Till konto</label>
        <input asp-for="recievingAccountNumber" class="form-control" />
        <span asp-validation-for="recievingAccountNumber" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Amount"></label>
        <input asp-for="Amount" class="form-control" />
        <span asp-validation-for="Amount" class="text-danger"></span>
    </div>
    <button type="submit" asp-action="Transfer">Överför</button>
</form>

<br />
<br />
<a asp-controller="Home" asp-action="Index" class="btn btn-primary">Tillbaka</a>

ArvidsBowling/Views/Transfer/TransferSuccess.cshtml
@model ArvidsBank.Models.Transfer.TransferVM
@{
    ViewData["Title"] = "Överföring Lyckades";
}

<div class="row">
    <div class="col-xs-12">
        <h1>Överföring lyckades</h1>
        <table>
            <tr>
                <th>Konto</th>
                <th>Saldo</th>
            </tr>
            <tr>
                <td>@Model.FromAccount.AccountNr</td>
                <td>@String.Format("{0:N}", @Model.FromAccount.Amount) kr</td>
            </tr>
            <tr>
                <td>@Model.RecievingAccount.AccountNr</td>
                <td>@String.Format("{0:N}", @Model.RecievingAccount.Amount)</td>
            </tr>
        </table>
    </div>
</div>

<br />
<br />
<a asp-controller="Home" asp-action="Index" class="btn btn-primary">Tillbaka</a>